<?php
return array (
  10 => 
  array (
    'id' => '10',
    'catid' => '12',
    'typeid' => '0',
    'title' => '雪地靴保养说明',
    'style' => '',
    'thumb' => '',
    'keywords' => '雪地',
    'description' => '雪地靴保养说明护理说明：1、 轻轻地用软布刷去表面的灰尘。2、 如果有必要的话、用湿润的海绵擦拭（如果有需要的话，可以加点肥皂），以   ',
    'posids' => '0',
    'url' => 'http://superbran.duapp.com/hangteng/index.php?m=content&c=index&a=show&catid=12&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'superbran',
    'inputtime' => '1482368316',
    'updatetime' => '1482368386',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '12',
    'typeid' => '0',
    'title' => '广州欢腾鞋业有限公司网站正式上线运营！',
    'style' => '',
    'thumb' => '',
    'keywords' => '广州 鞋业 网站',
    'description' => '广州欢腾鞋业有限公司网站正式上线运营！',
    'posids' => '0',
    'url' => 'http://superbran.duapp.com/hangteng/index.php?m=content&c=index&a=show&catid=12&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'superbran',
    'inputtime' => '1482368425',
    'updatetime' => '1482368436',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>