INSERT INTO `v9_category` VALUES('1','1','content','0','1','0','0','0','1','首页','','','','','index','http://superbran.duapp.com/linfen/index.php?m=content&c=index&a=lists&catid=1','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','shouye','');
INSERT INTO `v9_category` VALUES('2','1','content','0','1','0','0','0','2','公司业绩','','','','','achievement','http://superbran.duapp.com/linfen/index.php?m=content&c=index&a=lists&catid=2','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category-achievement\',
  \'list_template\' => \'list-achievement\',
  \'show_template\' => \'show-achievement\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','gongsiyeji','');
INSERT INTO `v9_category` VALUES('3','1','content','0','1','0','0','0','3','公司简介','','','','','about','http://superbran.duapp.com/linfen/index.php?m=content&c=index&a=lists&catid=3','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category-summary\',
  \'list_template\' => \'list-summary\',
  \'show_template\' => \'show-achievement\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','gongsijianjie','');
INSERT INTO `v9_category` VALUES('4','1','content','0','1','0','0','0','4','公司新闻','','','','','news','http://superbran.duapp.com/linfen/index.php?m=content&c=index&a=lists&catid=4','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category-news\',
  \'list_template\' => \'list-news\',
  \'show_template\' => \'show-news\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','4','1','0','gongsixinwen','');
