<?php
return array (
  1 => 
  array (
    'catid' => '1',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '1',
    'catname' => '首页',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'index',
    'url' => 'http://superbran.duapp.com/linfen/index.php?m=content&c=index&a=lists&catid=1',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '1',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'shouye',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  2 => 
  array (
    'catid' => '2',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '2',
    'catname' => '工程业绩',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'achievement',
    'url' => 'http://superbran.duapp.com/linfen/index.php?m=content&c=index&a=lists&catid=2',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category-achievement\',
  \'list_template\' => \'list-achievement\',
  \'show_template\' => \'show-achievement\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '2',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongchengyeji',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  3 => 
  array (
    'catid' => '3',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '3',
    'catname' => '公司简介',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'summary',
    'url' => 'http://superbran.duapp.com/linfen/index.php?m=content&c=index&a=lists&catid=3',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category-summary\',
  \'list_template\' => \'list-summary\',
  \'show_template\' => \'show-achievement\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '3',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongsijianjie',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  4 => 
  array (
    'catid' => '4',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '4',
    'catname' => '新闻中心',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'news',
    'url' => 'http://superbran.duapp.com/linfen/index.php?m=content&c=index&a=lists&catid=4',
    'items' => '1',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category-news\',
  \'list_template\' => \'list-news\',
  \'show_template\' => \'show-news\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '4',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xinwenzhongxin',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>